const TransObj = {    
    "ar": {
        "english_name":"Arabic",
        "section_labels": {"genre":"النوع","decade":"يعقد","provider":"مزود"},
        "trending":"رائج",
        "find":"يجد",
        "search":"ابحث",
        "movie": "فيلم",
        "movies": "أفلام",
        "tv":"تلفزيون",
        "tv_shows":"عرض تلفزيوني",
        "title":"عنوان",
        "all":"كل شئ",
        "sr-only": {
            "back_arrow":"سهم للخلف",
            "forward_arrow":"السهم إلى الأمام",
            "up_arrow":"سهم للاعلى",
            "down_arrow":"السهم لأسفل",
            "deactivated":"معطل",
            "eye_icon":"رمز العين",
            "film_icon":"أيقونة الفيلم",
            "tv_icon":"التلفزيون",
            "search_bar":"(ابحث)أيقونة العدسة المكبرة"
        },
        "error_messages":{"form_modal":"إختر خيار","no_results":"لا نتائج"},
        "provider_options": {"buy":"اشتريها","rent":"إيجار","stream":"يعرض الان","with_ads":"مع الإعلانات"}
    },
    "be": {
        "english_name":"Belarusian",
        "section_labels":{"genre":"Жанр","decade":"Дзесяцігоддзе","provider":"Правайдэр"},
        "trending":"у трэндзе",
        "find":"знаходзіць",
        "search":"шукаць",
        "movie":"фільм",
        "movies":"Фільмы",
        "tv":"TV",
        "tv_shows":"тэлеперадачы",
        "title":"назва",
        "all":"усё",
        "sr-only": {
            "back_arrow":"стрэлка назад",
            "forward_arrow":"стрэлка наперад",
            "up_arrow":"стрэлка ўверх",
            "down_arrow":"стрэлка ўніз",
            "deactivated":"дэактываваны",
            "eye_icon":"сімвал вачэй",
            "film_icon":"сімвал фільма",
            "tv_icon":"Тэлевізійны сімвал",
            "search_bar":"сімвал павелічальнага шкла (шукаць)"
        },
        "error_messages":{"form_modal":"Выберыце варыянт","no_results":"Няма вынікаў"},
        "provider_options": {"buy":"Купіць","rent":"Арэнда","stream":"Stream","with_ads":"З рэкламай"}
    },
    "bg": {
        "english_name":"Bulgarian",
        "section_labels":{"genre":"Жанр","decade":"Десетилетие","provider":"Доставчик"},
        "trending":"Набиращи популярност",
        "find":"намирам",
        "search":"търсене",
        "movie":"филм",
        "movies":"Филми",
        "tv":"TB",
        "tv_shows":"сериал",
        "title":"заглавие",
        "all":"Всичко",
        "sr-only": {
            "back_arrow":"стрелка назад",
            "forward_arrow":"стрелка напред",
            "up_arrow":"стрелка нагоре",
            "down_arrow":"стрелка надолу",
            "deactivated":"деактивиран",
            "eye_icon":"символ на очите",
            "film_icon":"Символ на филма",
            "tv_icon":"ТВ символ",
            "search_bar":"символ на лупа(търсене)"
        },
        "error_messages":{"form_modal":"Направете избор","no_results":"Няма резултати"},
        "provider_options": {"buy":"Купува","rent":"под наем","stream":"Стриймове","with_ads":"С реклами"}
    },
    "cs":{
        "english_name":"Czech",
        "section_labels":{"genre":"Žánr","decade":"Desetiletí","provider":"Poskytovatel"},
        "trending":"Nejnavštěvovanější",
        "find":"nalézt",
        "search":"hledat",
        "movie":"filmů",
        "movies":"filmy",
        "tv":"televize",
        "tv_shows":"TV pořady",
        "title":"název",
        "all":"Všechno",
        "sr-only": {
            "back_arrow":"šipka zpět",
            "forward_arrow":"šipka vpřed",
            "up_arrow":"šipka nahoru",
            "down_arrow":"šipka dolů",
            "deactivated":"deaktivován",
            "eye_icon":"symbol oka",
            "film_icon":"symbol filmu",
            "tv_icon":"symbol TV",
            "search_bar":"symbol lupy (hledat)"
        },
        "error_messages":{"form_modal":"Vyberte možnost","no_results":"Žádné výsledky"},
        "provider_options": {"buy":"Koupit","rent":"Pronajmout si","stream":"Streamované","with_ads":"S reklamami"}
    },
    "da": {
        "english_name":"Danish",
        "section_labels":{"genre":"Genre","decade":"Årti","provider":"Udbyder"},
        "trending":"Trending",
        "find":"finde",
        "search":"Søg",
        "movie":"film",
        "movies":"film",
        "tv":"TV",
        "tv_shows":"TV-serie",
        "title":"titel",
        "all":"Alt",
        "sr-only": {
            "back_arrow":"pil tilbage",
            "forward_arrow":"pil frem",
            "up_arrow":"pil op",
            "down_arrow":"pil ned",
            "deactivated":"deaktiveret",
            "eye_icon":"øje symbol",
            "film_icon":"film symbol",
            "tv_icon":"TV symbol",
            "search_bar":"forstørrelsesglas symbol"
        },
        "error_messages":{"form_modal":"Vælg en mulighed","no_results":"Ingen resultater"},
        "provider_options": {"buy":"Købe","rent":"Leje","stream":"Stream","with_ads":"Med annoncer"}
    },
    "de": {
        "english_name":"German",
        "section_labels":{"genre":"Genre","decade":"Jahrzehnt","provider":"Anbieter"},
        "trending":"Trends",
        "find":"finden",
        "search":"suchen",
        "movie":"Film",
        "movies":"Filme",
        "tv":"Serien",
        "tv_shows":"serie",
        "title":"Titel",
        "all":"Alles",
        "sr-only": {
            "back_arrow":"Zurück Pfeiltaste",
            "forward_arrow":"Vorwärtspfeiltaste",
            "up_arrow":"Pfeiltaste nach oben",
            "down_arrow":"Pfeiltaste nach unten",
            "deactivated":"deaktiviert",
            "eye_icon":"Augensymbol",
            "film_icon":"Filmsymbol",
            "tv_icon":"TV-Symbol",
            "search_bar":"Magnifying glass icon (suchen)"
        },
        "error_messages":{"form_modal":"Wähle eine Option","no_results":"No results"},
        "provider_options": {"buy":"Kaufen","rent":"Mieten","stream":"Stream","with_ads":"Mit Werbung"}
    },
    "el": {
        "english_name":"Greek",
        "section_labels":{"genre":"Είδος","decade":"Δεκαετία","provider":"Προμηθευτής"},
        "trending":"Τάσεις",
        "find":"βρίσκω",
        "search":"ζητώ",
        "movie":"ταινία",
        "movies":"Ταινίες",
        "tv":"Τηλεόραση",
        "tv_shows":"τηλεοπτικές εκπομπές",
        "title":"τίτλος",
        "all":"Τα παντα",
        "sr-only": {
            "back_arrow":"κουμπί βέλους προς τα πίσω",
            "forward_arrow":"κουμπί βέλους προς τα εμπρός",
            "up_arrow":"κουμπί επάνω βέλους",
            "down_arrow":"κουμπί κάτω βέλους",
            "deactivated":"απενεργοποιημένο",
            "eye_icon":"σύμβολο ματιών",
            "film_icon":"σύμβολο ταινίας",
            "tv_icon":"σύμβολο της τηλεόρασης",
            "search_bar":"σύμβολο μεγεθυντικού φακού (ζητώ)"
        },
        "error_messages":{"form_modal":"Διάλεξε μια επιλογή","no_results":"Δεν υπάρχουν αποτελέσματα που να ταιριάζουν"},
        "provider_options": {"buy":"Αγορά","rent":"Ενοίκιο","stream":"Σε ροή","with_ads":"Με διαφήμιση"}
    },
    "en": {
        "english_name":"English",
        "section_labels": {"genre":"Genre","decade":"Decade","provider":"Provider"},
        "trending":"Trending",
        "find":"Find",
        "search":"Search",
        "person":"person's name",
        "movie":"movie",
        "movies":"movies",
        "tv":"TV",
        "tv_shows":"TV Shows",
        "title":"title",
        "sr-only": {
            "back_arrow":"back arrow",
            "forward_arrow":"forward arrow",
            "up_arrow":"up arrow",
            "down_arrow":"down arrow",
            "deactivated":"deactivated",
            "eye_icon":"eye icon",
            "film_icon":"film icon",
            "tv_icon":"TV icon",
            "search_bar":"magnifying glass icon (search)"
        },
        "error_messages":{"form_modal":"Make a selection","no_results":"No results"},
        "provider_options": {"buy":"Buy","rent":"Rent","stream":"Stream","with_ads":"With Ads"}
    },
    "es": {
        "english_name":"Spanish",
        "section_labels":{"genre":"Género","decade":"Década","provider":"Proveedor"},
        "trending":"tendencias",
        "find":"encontrar",
        "movie":"película",
        "movies":"películas",
        "tv":"tele",
        "tv_shows":"programas de televisión",
        "title":"título",
        "all":"Todo",
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Comprar","rent":"Alquilar","stream":"Retransmisión","with_ads":""}
    },
    "fi": {
        "english_name":"Finnish",
        "section_labels":{"genre":"Genre","decade":"Vuosikymmen","provider":"Palveluntarjoaja"},
        "trending":"Nousussa",
        "find":"etsiä",
        "movie":"elokuva",
        "movies":"elokuvia",
        "tv":"televisio",
        "tv_shows":"televisio-ohjelmat",
        "title":"nimi",
        "all":"Kaikki", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Ostaa","rent":"Vuokrata","stream":"Striimattavana","with_ads":""}
    },
    "fr": {
        "english_name":"French",
        "section_labels":{"genre":"Genre","decade":"Décennie","provider":"Fournisseur"},
        "trending":"tendance",
        "search":"chercher",
        "find":"trouver",
        "movie":"film",
        "movies":"​les films",
        "tv":"la télé",
        "tv_shows":"Séries TV",
        "title":"titre",
        "all":"Tout",
        "sr-only": {
            "back_arrow":"flèche vers l'arrière",
            "forward_arrow":"flèche vers l'avant",
            "up_arrow":"flèche vers le haut",
            "down_arrow":"flèche vers le bas",
            "deactivated":"désactivé",
            "eye_icon":"symbole de l'oeil",
            "film_icon":"symbole du film",
            "tv_icon":"Symbole de la télévision",
            "search_bar":"symbole de la loupe (chercher)"
        },
        "error_messages":{"form_modal":"Choisissez","no_results":"Aucun résultat"},
        "provider_options": {"buy":"Acheter","rent":"Louer","stream":"Stream","with_ads":"avec des publicités"}
    },
    "he": {
        "english_name":"Hebrew",
        "section_labels":{"genre":"ז'ָאנר","decade":"עָשׂוֹר","provider":"מֵפִיץ"},
        "trending":"מגמתי",
        "find":"",
        "movie":"סרט",
        "movies":"סרטים",
        "tv":"טלוויזיה",
        "tv_shows":"סדרה",
        "title":"",
        "all":"הכל", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"לִקְנוֹת","rent":"השכרה","stream":"הזרמה","with_ads":""}
    },
    "hu": {
        "english_name":"Hungarian",
        "section_labels":{"genre":"Műfaj","decade":"Évtized","provider":"Szolgáltató"},
        "trending":"Népszerű",
        "find":"",
        "movie":"film",
        "movies":"Filmek",
        "tv":"Tévé",
        "tv_shows":"tévéműsor",
        "title":"",
        "all":"Minden", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"megvesz","rent":"Bérlés","stream":"Stream","with_ads":""}
    },
    "id": {
        "english_name":"Indonesian",
        "section_labels":{"genre":"Genre","decade":"Dasawarsa","provider":"Pemasok"},
        "trending":"Trending",
        "find":"Cari",
        "search":"Cari",
        "person":"kru / aktor",
        "movie":"film",
        "movies":"film",
        "tv":"televisi",
        "tv_shows":"serial tv",
        "title":"Judul",
        "all":"Semuanya", 
        "sr-only": {
            "back_arrow":"panah kembali",
            "forward_arrow":"panah ke depan",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"simbol mata",
            "film_icon":"simbol film",
            "tv_icon":"simbol televisi",
            "search_bar":"simbol kaca pembesar (Cari)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Membeli","rent":"Menyewa","stream":"Stream", "with_ads":"dengan iklan"}
    },
    "it": {
        "english_name":"Italian",
        "section_labels":{"genre":"Genere","decade":"Decennio","provider":"Fornitore"},
        "trending":"Di tendenza",
        "find":"",
        "movie":"film",
        "movies":"films",
        "tv":"Serie TV",
        "tv_shows":"Serie TV",
        "title":"",
        "all":"Qualunque cosa", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Acquistare","rent":"Affitto","stream":"Stream","with_ads":""}
    },
    "ja": {
        "english_name":"Japanese",
        "section_labels": {"genre":"ジャンル","decade":"十年","provider":"プロバイダー"},
        "trending":"動向",
        "find":"",
        "movie":"映画",
        "movies":"映画",
        "tv":"テレビ",
        "tv_shows":"テレビ番組",
        "title":"名",
        "all":"すべて", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"買う","rent":"家賃","stream":"ストリーミング","with_ads":""}
    },
    "ka": {
        "english_name":"Georgian",
        "section_labels": {"genre":"ჟანრი","decade":"ათწლეული","provider":"პროვაიდერი"},
        "trending":"Trending",
        "find":"",
        "person":"პიროვნება",
        "movie":"ფილმი",
        "movies":"ფილმები",
        "tv":"TV",
        "tv_shows":"სერიალი",
        "title":"",
        "all":"ყველაფერი", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"იყიდე","rent":"Ქირავდება","stream":"Stream","with_ads":""}
    },
    "ko": {
        "english_name":"Korean",
        "section_labels": {"genre":"장르","decade":"10년","provider":"공급자"},
        "trending":"트렌딩",
        "find":"검색",
        "search":"검색",
        "person":"인물",
        "movie":"영화",
        "movies":"영화",
        "tv":"TV",
        "tv_shows":"TV 프로그램",
        "title":"제목",
        "all":"모든 것", 
        "sr-only": {
            "back_arrow":"뒤로 화살표",
            "forward_arrow":"앞으로 화살표",
            "up_arrow":"위쪽 화살표",
            "down_arrow":"아래쪽 화살표",
            "deactivated":"비활성화됨",
            "eye_icon":"눈 기호",
            "film_icon":"영화의 상징",
            "tv_icon":"TV 기호",
            "search_bar":"돋보기 기호 (검색)"
        },
        "error_messages":{"form_modal":"옵션을 선택하세요","no_results":"결과가 없다"},
        "provider_options": {"buy":"구입하다","rent":"임대","stream":"스트리밍", "with_ads":"광고와 함께"}
    },
    "lt": {
        "english_name":"Lithuanian",
        "section_labels": {"genre":"Žanras","decade":"Dešimtmetis","provider":"Teikėjas"},
        "trending":"Tendencijos",
        "find":"",
        "person":"asmens",
        "movie":"filmo",
        "movies":"Filmai",
        "tv":"TV",
        "tv_shows":"tv laidos",
        "title":"",
        "all":"Viskas", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Pirkti","rent":"Nuoma","stream":"Internetu", "with_ads":""}
    },
    "nl": {
        "english_name":"Dutch",
        "section_labels": {"genre":"Genre","decade":"Decennium","provider":"Aanbieder"},
        "trending":"Trending",
        "find":"vinden",
        "search":"Zoeken",
        "person":"persoon",
        "movie":"film",
        "movies":"films",
        "tv":"TV",
        "tv_shows":"tv-serie",
        "title":"titel",
        "all":"Alles", 
        "sr-only": {
            "back_arrow":"pijl terug",
            "forward_arrow":"pijl vooruit",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"oogpictogram",
            "film_icon":"film pictogram",
            "tv_icon":"tv-pictogram",
            "search_bar":"vergrootglaspictogram(Zoeken)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Kopen","rent":"Huur","stream":"Stream","with_ads":""}
    },
    "pl": {
        "english_name":"Polish",
        "section_labels": { "genre":"Gatunek","decade":"Dekada","provider":"Dostawca"},
        "trending":"Trending",
        "search":"Szukaj",
        "find":"odszukać",
        "person":"osoby",
        "movie":"filmu",
        "movies":"filmy",
        "tv":"TV",
        "tv_shows":"serialu",
        "title":"tytuł",
        "all":"Wszystko", 
        "sr-only": {
            "back_arrow":"strzałka wstecz",
            "forward_arrow":"strzałka do przodu",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"symbol oka",
            "film_icon":"symbol filmu",
            "tv_icon":"symbol telewizora",
            "search_bar":"symbol szkła powiększającego (Szukaj)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Kupić","rent":"Wynajem","stream":"Stream","with_ads":""}
    },
    "pt": {
        "english_name":"Portuguese",
        "section_labels": {"genre":"Gênero","decade":"Década","provider":"Fornecedor"},
        "trending":"Tendências",
        "find":"buscar",
        "search":"Pesquisar",
        "person":"pessoa",
        "movie":"filme",
        "movies":"Filmes",
        "tv":"Na TV",
        "tv_shows":"série televisiva",
        "title":"título",
        "all":"Tudo", 
        "sr-only": {
            "back_arrow":"seta para trás",
            "forward_arrow":"seta para frente",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"símbolo do olho",
            "film_icon":"símbolo do filme",
            "tv_icon":"símbolo de televisão",
            "search_bar":"magnifying glass symbol (Pesquisar)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Comprar","rent":"Aluguel","stream":"Stream","with_ads":"com anúncios"}
    },
    "ro": {
        "english_name":"Romanian",
        "section_labels": {"genre":"Gen","decade":"Deceniu","provider":"Furnizor"},
        "trending":"Tendință",
        "find":"",
        "person":"",
        "movie":"",
        "movies":"Filme",
        "tv":"Seriale",
        "tv_shows":"serial sau",
        "title":"",
        "all":"Tot", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":"",
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Cumpără","rent":"Chirie","stream":"Stream", "with_ads":""}
    },
    "ru": {
        "english_name":"Russian",
        "section_labels": {"genre":"Жанр","decade":"Десятилетие","provider":"Поставщик"},
        "trending":"В тренде",
        "find":"Найти",
        "search":"искать",
        "person":"персону",
        "movie":"фильм",
        "movies":"Фильмы",
        "tv":"Сериалы",
        "tv_shows":"сериал",
        "title":"название",
        "all":"Все", 
        "sr-only": {
            "back_arrow":"стрелка назад",
            "forward_arrow":"стрелка вперед",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"символ глаза",
            "film_icon":"символ фильма",
            "tv_icon":"символ телевизора",
            "search_bar":"символ увеличительного стекла (искать)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Купить","rent":"Арендовать","stream":"Онлайн", "with_ads":"с рекламой"}
    },
    "sk": {
        "english_name":"Slovak",
        "section_labels": {"genre":"Žánru","decade":"desaťročie","provider":"Poskytovateľ"},
        "trending":"Trendujúce",
        "find":"Hľadať",
        "search":"Hľadať",
        "person":"osobu",
        "movie":"film",
        "movies":"Filmy",
        "tv":"TV",
        "tv_shows":"seriál",
        "title":"titul",
        "all":"Všetko", 
        "sr-only": {
            "back_arrow":"šípka dozadu",
            "forward_arrow":"šípka dopredu",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"symbol oka",
            "film_icon":"symbol filmu",
            "tv_icon":"symbol TV",
            "search_bar":"symbol lupy (Hľadať)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Kúpiť","rent":"Nájomné","stream":"Streamované", "with_ads":"s reklamami"}
    },
    "sl": {
        "english_name":"Slovenian",
        "section_labels": {"genre":"Žanr","decade":"desetletje","provider":"Ponudnik"},
        "trending":"Trending",
        "find":"raziskovati",
        "search":"raziskovati",
        "person":"oseba",
        "movie":"film",
        "movies":"filmi",
        "tv":"TV",
        "tv_shows":"tv oddaje",
        "title":"naslov",
        "all":"Vse", 
        "sr-only": {
            "back_arrow":"puščica nazaj",
            "forward_arrow":"puščica naprej",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"simbol oči",
            "film_icon":"filmski simbol",
            "tv_icon":"tv simbol",
            "search_bar":"simbol povečevalnega stekla (raziskovati)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Nakup","rent":"Najemnina","stream":"Stream", "with_ads":"z oglasi"}
    },
    "sr": {
        "english_name":"Serbian",
        "section_labels": {"genre":"Жанр","decade":"Декада","provider":"Провајдер"},
        "trending":"У тренду",
        "find":"",
        "person":"",
        "movie":"",
        "movies":"Филмови",
        "tv":"ТВ",
        "tv_shows":"серију",
        "title":"",
        "all":"Све", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Купи","rent":"Закуп","stream":"Стрим","with_ads":""}
    },
    "sv": {
        "english_name":"Swedish",
        "section_labels": {"genre":"Genre","decade":"Årtionde","provider":"Leverantör"},
        "trending":"Trendande",
        "find":"",
        "movie":"",
        "movies":"Filmer",
        "tv":"TV",
        "tv_shows":"tv-serie",
        "title":"",
        "all":"Allt", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"köpa","rent":"Hyra","stream":"Strömmas","with_ads":""}
    },
    "th": {
        "english_name":"Thai",
        "section_labels": {"genre":"ประเภท","decade":"ทศวรรษ","provider":"ผู้ให้บริการ"},
        "trending":"Trending",
        "find":"สอบถาม",
        "serach":"สอบถาม",
        "person":"บุคคล",
        "movie":"ภาพยนตร์",
        "movies":"ภาพยนตร์",
        "tv":"โทรทัศน์",
        "tv_shows":"รายการโทรทัศน์",
        "title":"ชื่อ",
        "all":"ทุกอย่าง", 
        "sr-only": {
            "back_arrow":"ลูกศรย้อนกลับ",
            "forward_arrow":"ลูกศรไปข้างหน้า",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"สัญลักษณ์ตา",
            "film_icon":"สัญลักษณ์ภาพยนตร์",
            "tv_icon":"สัญลักษณ์ทีวี",
            "search_bar":"สัญลักษณ์แว่นขยาย (สอบถาม)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"ซื้อ","rent":"เช่า","stream":"Stream", "with_ads":"ด้วยโฆษณา"}

    },
    "tr": {
        "english_name":"Turkish",
        "section_labels": {"genre":"Tür","decade":"On yıl","provider":"Sağlayıcı"},
        "trending":"Trend",
        "find":"bakmak",
        "search":"ara",
        "person":"kişi",
        "movie":"film",
        "movies":"Filmler",
        "tv":"TV",
        "tv_shows":"dizi",
        "title":"başlığı",
        "all":"Her şey", 
        "sr-only": {
            "back_arrow":"geri ok",
            "forward_arrow":"ileri ok",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"göz sembolü",
            "film_icon":"film sembolü",
            "tv_icon":"televizyon sembolü",
            "search_bar":"büyüteç sembolü (ara)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Satın almak","rent":"Kira","stream":"Yayın Akışı", "with_ads":"reklamlarla"}
    },
    "vi": {
        "english_name":"Vietnamese",
        "section_labels": {"genre":"thể loại","decade":"Thập kỷ","provider":"Các nhà cung cấp"},
        "trending":"Trending",
        "find":"tìm kiếm",
        "search":"tìm kiếm",
        "person":"người",
        "movie":"phim",
        "movies":"phim",
        "tv":"TV",
        "tv_shows":"truyền hình nhiều tập",
        "title":"tên",
        "all":"Mọi thứ", 
        "sr-only": {
            "back_arrow":"Mũi tên quay lại",
            "forward_arrow":"mũi tên tiến",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"biểu tượng mắt",
            "film_icon":"biểu tượng phim",
            "tv_icon":"biểu tượng tivi",
            "search_bar":"biểu tượng kính lúp (tìm kiếm)"
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"Mua","rent":"Thuê","stream":"Stream","with_ads":"với quảng cáo"}
    },
    "zh": {
        "english_name":"Mandarin",
        "section_labels": {"genre":"类型","decade":"十年","provider":"提供者"},
        "trending":"趋势",
        "find":"",
        "person":"",
        "movie":"电影",
        "movies":"电影",
        "tv":"电视",
        "tv_shows":"剧集",
        "title":"",
        "all":"一切", 
        "sr-only": {
            "back_arrow":"",
            "forward_arrow":"",
            "up_arrow":"",
            "down_arrow":"",
            "deactivated":"",
            "eye_icon":"",
            "film_icon":"",
            "tv_icon":"",
            "search_bar":""
        },
        "error_messages":{"form_modal":"","no_results":""},
        "provider_options": {"buy":"买","rent":"租","stream":"流媒体","with_ads":""}
    }
}

export { TransObj }
