// function Translations({ currentLanguage }) {
//     const [langCode, nativeName, englishName] = currentLanguage;
    
//     return (
//         transObj.langCode
//     )
// }

const TransObj = {    
    "ar": {
        "english_name":"Arabic",
        "genre":"النوع",
        "decade":"يعقد",
        "provider":"مزود",
        "tending":"الشائع",
        "find":"يجد",
        "search":"اكتشف",
        "movie": "فيلم",
        "movies": "أفلام",
        "tv":"تلفزيون",
        "tv-shows":"عرض تلفزيوني",
        "title":"عنوان",
        "titles":"العناوين"
    },
    "be": {
        "english_name":"Belarusian",
        "genre":"Жанр",
        "decade":"Дзесяцігоддзе",
        "provider":"Правайдэр",
        "tending":"у трэндзе",
        "find":"знаходзіць",
        "search":"шукаць",
        "movie":"фільм",
        "movies":"фільмы",
        "tv":"тэлевізар",
        "tv-shows":"тэлеперадачы",
        "title":"назва",
        "titles":"назвы"
    },
    "bg": {
        "english_name":"Bulgarian",
        "genre":"Жанр",
        "decade":"Десетилетие", 
        "provider":"Доставчик",
        "tending":"в тенденция",
        "find":"намирам",
        "search":"обискирам",
        "movie":"филм",
        "movies":"филми",
        "tv":"телевизия",
        "tv-shows":"телевизионни предавания",
        "title":"заглавие",
        "titles":"заглавия"
    },
    "cs":{
        "english_name":"Czech", 
        "genre":"Žánr",
        "decade":"Desetiletí",
        "provider":"Poskytovatel",
        "tending":"trendy",
        "find":"nalézt",
        "search":"hledat",
        "movie":"filmů",
        "movies":"filmy",
        "tv":"televize",
        "tv-shows":"TV pořady",
        "title":"název",
        "titles":"názvy"
    },
    "da": {
        "english_name":"Danish",
        "genre":"Genre",
        "decade":"Årti",
        "provider":"Udbyder",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"film",
        "movies":"film",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "de": {
        "english_name":"German",
        "genre":"Genre",
        "decade":"Jahrzehnt",
        "provider":"Anbieter",
        "tending":"im Trend",
        "find":"finden",
        "search":"suchen",
        "movie":"Film",
        "movies":"Filme",
        "tv":"Fernsehen",
        "tv-shows":"Fernsehsendungen",
        "title":"Titel",
        "titles":"Titel"
    },
    "el": {
        "english_name":"Greek",
        "genre":"Είδος",
        "decade":"Δεκαετία",
        "provider":"Προμηθευτής",
        "tending":"τάσεις",
        "find":"βρίσκω",
        "search":"ζητώ",
        "movie":"κινηματογράφος",
        "movies":"κινηματογράφος",
        "tv":"τηλεόραση",
        "tv-shows":"τηλεοπτικές εκπομπές",
        "title":"τίτλος",
        "titles":"τίτλος"
    },
    "en": {
        "english_name":"English",
        "genre":"Genre",
        "decade":"Decade",
        "provider":"Provider",
        "tending":"Trending",
        "find":"Find",
        "search":"Search",
        "movie":"movie",
        "movies":"movies",
        "tv":"TV",
        "tv-shows":"TV Shows",
        "title":"title",
        "titles":"titles"
    },
    "es": {
        "english_name":"Spanish",
        "genre":"Género",
        "decade":"Década",
        "provider":"Proveedor",
        "tending":"tendencias",
        "find":"encontrar",
        "search":"buscar",
        "movie":"película",
        "movies":"películas",
        "tv":"tele",
        "tv-shows":"programas de televisión",
        "title":"título",
        "titles":"títulos"
    },
    "fi": {
        "english_name":"Finnish",
        "genre":"Genre",
        "decade":"Vuosikymmen",
        "provider":"Palveluntarjoaja",
        "tending":"trendikkäitä",
        "find":"etsiä",
        "search":"etsiä",
        "movie":"elokuva",
        "movies":"elokuvia",
        "tv":"televisio",
        "tv-shows":"televisio-ohjelmat",
        "title":"nimi",
        "titles":""
    },
    "fr": {
        "english_name":"French",
        "genre":"Genre",
        "decade":"Décennie",
        "provider":"Fournisseur",
        "tending":"tendance",
        "find":"trouver",
        "search":"chercher",
        "movie":"film",
        "movies":"​les films",
        "tv":"la télé",
        "tv-shows":"émissions de télévision",
        "title":"titre",
        "titles":"titres"
    },
    "he": {
        "english_name":"Hebrew",
        "genre":"ז'ָאנר",
        "decade":"עָשׂוֹר",
        "provider":"מֵפִיץ",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    }
        ,
    "hu": {
        "english_name":"Hungarian",
        "genre":"Műfaj",
        "decade":"Évtized",
        "provider":"Szolgáltató",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "id": {
        "english_name":"Indonesian",
        "genre":"Genre",
        "decade":"Dasawarsa",
        "provider":"Pemasok",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "it": {
        "english_name":"Italian",
        "genre":"Genere",
        "decade":"Decennio",
        "provider":"Fornitore",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "ja": {
        "english_name":"Japanese",
        "genre":"ジャンル",
        "decade":"十年",
        "provider":"プロバイダー",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "ka": {
        "english_name":"Georgian",
        "genre":"ჟანრი",
        "decade":"ათწლეული",
        "provider":"პროვაიდერი",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "ko": {
        "english_name":"Korean",
        "genre":"장르",
        "decade":"10년",
        "provider":"공급자",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "lt": {
        "english_name":"Lithuanian",
        "genre":"Žanras",
        "decade":"Dešimtmetis",
        "provider":"Teikėjas",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "nl": {
        "english_name":"Dutch",
        "genre":"Genre",
        "decade":"Decennium",
        "provider":"Aanbieder",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "pl": {"english_name":"Polish",
    "genre":"Gatunek",
    "decade":"Dekada",
    "provider":"Dostawca",
    "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "pt": {
        "english_name":"Portuguese",
        "genre":"Gênero",
        "decade":"Década",
        "provider":"Fornecedor",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "ro": {
        "english_name":"Romanian",
        "genre":"Gen",
        "decade":"Deceniu",
        "provider":"Furnizor",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "ru": {
        "english_name":"Russian",
        "genre":"Жанр",
        "decade":"Десятилетие",
        "provider":"Поставщик",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "sk": {
        "english_name":"Slovak",
        "genre":"Žánru",
        "decade":"desaťročie",
        "provider":"Poskytovateľ",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "sl": {
        "english_name":"Slovenian",
        "genre":"Žanr",
        "decade":"desetletje",
        "provider":"Ponudnik",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "sr": {
        "english_name":"Serbian",
        "genre":"Жанр",
        "decade":"Декада",
        "provider":"Провајдер",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "sv": {
        "english_name":"Swedish",
        "genre":"Genre",
        "decade":"Årtionde",
        "provider":"Leverantör",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "th": {
        "english_name":"Thai",
        "genre":"ประเภท",
        "decade":"ทศวรรษ",
        "provider":"ผู้ให้บริการ",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "tr": {
        "english_name":"Turkish",
        "genre":"Tür",
        "decade":"On yıl",
        "provider":"Sağlayıcı",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "vi": {
        "english_name":"Vietnamese",
        "genre":"thể loại",
        "decade":"Thập kỷ",
        "provider":"Các nhà cung cấp",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    },
    "zh": {
        "english_name":"Mandarin",
        "genre":"类型",
        "decade":"十年",
        "provider":"提供者",
        "tending":"",
        "find":"",
        "search":"",
        "movie":"",
        "movies":"",
        "tv":"",
        "tv-shows":"",
        "title":"",
        "titles":""
    }
}

export { TransObj }
